### ISSUE TITLE
Add code for Fragment Transition

### ISSUE THREAD

**Issue by KaranVerma2000** [DSC-JSS-NOIDA/EasyLinks#7]
In Main Activity, upon clicking search icon in bottom bar Search Fragment should open and Profile Fragment should open upon clicking the profile icon. Profile Fragment is default fragment. Use **Support Fragment Manager** for transitions.

**Comment by mjmadhur** [comment]
Can i solve this

**Comment by nakul-19** [comment]
Thanks for showing your interest in the issue.
